#! /bin/sh

PATH="$PATH:/home/<username>/asuswrt-merlin/release/src-rt-6.x.4708/toolchains/hndtools-arm-linux-2.6.36-uclibc-4.5.3/bin"

cd $HOME/asuswrt-merlin && git clean -dxf && git reset --hard

## patch because of newer awk in Artix; Makefile.in need to be patched not Makefile.am (not used)!
patch -p1 -d$HOME/asuswrt-merlin/release/src/router/libgpg-error-1.10 < $HOME/Dokumente/asuswrt/libgpg-error.patch 

cp $HOME/Dokumente/asuswrt/wlconf $HOME/asuswrt-merlin/release/src/router/wlconf_arm/prebuilt

patch -i $HOME/Dokumente/asuswrt/Makefile.patch $HOME/asuswrt-merlin/release/src/router/Makefile

cp -r $HOME/Dokumente/asuswrt/wget/ $HOME/asuswrt-merlin/release/src/router

rm $HOME/asuswrt-merlin/release/src/router/openssl/Makefile

cd release/src-rt-6.x.4708 && make rt-ac56u
